# Build a System
# Lyrics Printing: Specific Songs

while True:
    song = input("\n Please choose a song: \n 1) Fourth of July - Sufjan Stevens \n 2) Gilded Lily - Cults \n "
             "3) Romantic Homicide - d4vd \n 4) O My Heart - Mother Mother \n 5) Beautiful Is Boring - BONES UK \n "
                 "6) Yes to Heaven - Lana Del Rey \n 7) Runaway - AURORA \n 8) we fell in love in october - girl in red \n\n"
             "[1 / 2 / 3 / 4 / 5 / 6 / 7 / 8]?: ")
    if song == "1":
        def lyric(repeat):
            print("\nFourth of July")
            print("by Sufjan Stevens")
            print("\nThe evil it spread like a fever ahead")
            print("It was night when you died, my firefly")
            print("What could I have said to raise you from the dead?")
            print("Oh could I be the sky on the Fourth of July?")
            print("\nWell you do enough talk")
            print("My little hawk, why do you cry?")
            print("Tell me what did you learn from the Tillamook burn?")
            print("Or the Fourth of July?")
            print(repeat)
            print("\nSitting at the bed with the halo at your head")
            print("Was it all a disguise, like Junior High")
            print("Where everything was fiction, future, and prediction")
            print("Now, where am I?")
            print("My fading supply")
            print("\nDid you get enough love, my little dove")
            print("Why do you cry?")
            print("And I'm sorry I left, but it was for the best")
            print("Though it never felt right")
            print("My little Versailles")
            print("\nThe hospital asked should the body be cast")
            print("Before I say goodbye, my star in the sky")
            print("Such a funny thought to wrap you up in cloth")
            print("Do you find it all right, my dragonfly?")
            print("\nShall we look at the moon, my little loon")
            print("Why do you cry?")
            print("Make the most of your life, while it is rife")
            print("While it is light")
            print("\nWell you do enough talk")
            print("My little hawk, why do you cry?")
            print("Tell me what did you learn from the Tillamook burn?")
            print("Or the Fourth of July?")
            print(repeat)
            print()
            print(repeat)
            print(repeat)
            print(repeat)
            print(repeat)
            print(repeat)
            print(repeat)
            print(repeat)
        lyric("We're all gonna die")
    elif song == "2":
        def lyric(repeat):
            def lyric(repeat2):
                print("\nGilded Lily")
                print("by Cults")
                print("\nNow it's been long enough to talk about it")
                print("I've started not to doubt it, just wrap my head around it")
                print("I remember when you told me it's an everyday decision")
                print("But with my double vision, how was I supposed to see the way?")
                print()
                print(repeat)
                print(repeat)
                print(repeat)
                print(repeat)
                print()
                print(repeat2)
                print()
                print("Every city's got a graveyard")
                print("The service bought and paid for")
                print("Now I'm sleeping in the backyard")
                print("Passing out as light turns into day")
                print()
                print(repeat)
                print(repeat)
                print(repeat)
                print(repeat)
                print()
                print(repeat2)
                print()
                print("Go and stretch out my arms")
                print("Long as they need to be")
                print("Turn off all alarms and lie to me")
                print("\nGo and stretch out my arms")
                print("Long as they need to be")
                print("Turn off all alarms and lie to me")
                print()
                print(repeat)
                print(repeat)
                print(repeat)
                print(repeat)
                print()
                print("Always the fool with the slowest heart")
                print("But I know you'll take me with you")
                print("I know I'll take you with me")
                print()
                print(repeat2)
            lyric("Always the fool with the slowest heart \nBut I know you'll take me with you \nWe'll live in spaces between walls")
        lyric("Haven't I given enough, given enough?")
    elif song == "3":
        def lyric(repeat):
            print("\nRomantic Homicide")
            print("by d4vd")
            print("\nI'm scared (Oh-oh-oh)")
            print("It feels like you don't care (Ooh-ooh)")
            print("Enlighten me, my dear (Ooh-ooh-ooh)")
            print("Why am I still here? Mm (Oh-oh)")
            print("I don't mean to be")
            print("Complacent with the decisions you made")
            print("But why? Mm")
            print()
            print(repeat)
            print("You died")
            print("And I didn't even cry")
            print("No, not a single tear")
            print("And I'm sick of waiting patiently")
            print("For someone that won't even arrive")
            print("\nOoh-ooh-ooh-ooh-ooh")
            print()
            print(repeat)
            print("I killed you")
            print("And I didn't even regret it")
            print("I can't believe I said it")
            print("But it's true")
            print("I hate you")
        lyric("In the back of my mind")
    elif song == "4":
        def lyric(repeat):
            def lyric(repeat2):
                def lyric(repeat3):
                    print("\nO My Heart")
                    print("by Mother Mother")
                    print()
                    print(repeat, "fish out of water")
                    print(repeat, "fish on the rocks and it bakes in the bad sun")
                    print(repeat, "rock in the gutter")
                    print(repeat, "rocking great bolder and stuck in the gutter")
                    print("\nAnd I throw my heart back to the ocean")
                    print("But it don't go far it come back floating")
                    print("And I watch it wash up with the dead fish")
                    print("But it ain't quite dead it just is lifeless")
                    print()
                    print(repeat, "house in tornado")
                    print(repeat, "house in the sky in the eye of tornado")
                    print(repeat, "roof in el niño")
                    print(repeat, "roof made of straw in the jaw of el niño")
                    print("\nAnd I pour my heart a new foundation")
                    print("But it don't set hard it just stays shaking")
                    print("And I scratch my name I scratch my name in")
                    print("But it don't set hard it gets mixed back in")
                    print()
                    print(repeat2)
                    print(repeat3)
                    print(repeat2)
                    print(repeat3)
                    print(repeat3)
                    print(repeat2)
                    print()
                    print(repeat, "fish out of water")
                    print(repeat, "rock in the gutter")
                    print(repeat, "black in a rainbow")
                    print("Oh my heart, it's so damn cold")
                    print("\nAnd I throw my heart into the fire")
                    print("'Cause I want to set my heart on fire")
                    print("And I watch it try befriending embers")
                    print("But the ice don't melt in mid December")
                    print()
                    print(repeat, "fish out of water")
                    print(repeat, "fish on the rocks and it bakes in the bad sun")
                lyric("Bum, bum, bum, bum, bum, bum")
            lyric("Bum, bum, bum")
        lyric("Oh my heart, it's a")
    elif song == "5":
        def lyric(repeat):
            def lyric(repeat2):
                def lyric(repeat3):
                    print("\nBeautiful Is Boring")
                    print("by BONES UK")
                    print()
                    print(repeat)
                    print(repeat)
                    print(repeat)
                    print(repeat)
                    print("\nBeautiful")
                    print("They said they did not want my face in their magazine")
                    print("'Cause I'm not beautiful")
                    print("Am I the most fucking fantastic freak")
                    print("You've ever seen? Did I make you scream?")
                    print("\nDo we make you sick?")
                    print("Do our imperfections make your blue breath run thick?")
                    print("Give me scars and stripes")
                    print("It does not please me to be easy on any of your eyes")
                    print("Any of your eyes")
                    print()
                    print(repeat2)
                    print(repeat2)
                    print(repeat2)
                    print(repeat2)
                    print()
                    print(repeat)
                    print(repeat)
                    print("\nFall flawless to the floor")
                    print("Shady lady gave me 'Ketones' so I might be decor")
                    print("Just pass me my cigar")
                    print("Teaching children to be anything")
                    print("Other than who they are, who they are")
                    print()
                    print(repeat2)
                    print(repeat2)
                    print(repeat2)
                    print(repeat2)
                    print()
                    print(repeat)
                    print(repeat3)
                    print(repeat)
                    print(repeat)
                    print(repeat)
                    print(repeat3)
                    print()
                    print(repeat2)
                    print(repeat2)
                    print(repeat2)
                    print(repeat2)
                lyric("You're never gunna save their souls")
            lyric("Beautiful, Beautiful Is Boring")
        lyric("You're never gunna save those soul suckers")
    elif song == "6":
        def lyric(repeat):
            def lyric(repeat2):
                def lyric(repeat3):
                    def lyric(repeat4):
                        def lyric(repeat5):
                            print("\nYes to Heaven")
                            print("by Lana Del Rey")
                            print()
                            print(repeat)
                            print("And if you don't I'll dance anyway")
                            print("Give peace a chance")
                            print("Let the fear you have fall away")
                            print()
                            print(repeat2)
                            print(repeat2)
                            print()
                            print(repeat3)
                            print(repeat4)
                            print(repeat3)
                            print(repeat4)
                            print("\nIf you go I'll stay")
                            print("You come back I'll be right here")
                            print("Like a barge at sea")
                            print("In the storm I stay clear")
                            print("\n'Cause", repeat5)
                            print(repeat5)
                            print()
                            print(repeat3)
                            print(repeat4)
                            print(repeat3)
                            print(repeat4)
                            print()
                            print(repeat)
                            print("I'll put my red dress on again")
                            print("And if you fight I'll fight")
                            print("It doesn't matter, now it's all gone")
                            print()
                            print(repeat5)
                            print(repeat5)
                            print()
                            print(repeat3)
                            print(repeat4)
                            print(repeat3)
                            print(repeat4)
                            print()
                            print(repeat2)
                            print(repeat2)
                        lyric("I've got my mind on you")
                    lyric("Say yes to me")
                lyric("Say yes to heaven")
            lyric("I've got my eye on you")
        lyric("If you dance I'll dance")
    elif song == "7":
        def lyric(repeat):
            def lyric(repeat2):
                def lyric(repeat3):
                    def lyric(repeat4):
                        def lyric(repeat5):
                            def lyric(repeat6):
                                def lyric(repeat7):
                                    def lyric(repeat8):
                                        def lyric(repeat9):
                                            def lyric(repeat10):
                                                print("\nRunaway")
                                                print("by AURORA")
                                                print("\nI was listenin' to the ocean")
                                                print("I saw a face in the sand")
                                                print("But when I picked it up")
                                                print("Then it vanished away from my hands, dah")
                                                print("\nI had a dream, I was seven")
                                                print("Climbin' my way in a tree")
                                                print("I saw a piece of Heaven")
                                                print("Waitin' in patience for me, dah")
                                                print()
                                                print(repeat)
                                                print(repeat2)
                                                print(repeat3)
                                                print(repeat4)
                                                print(repeat5)
                                                print("\nBut no, take me home")
                                                print(repeat6)
                                                print(repeat7)
                                                print(repeat8)
                                                print("\nI was painting a picture")
                                                print("The picture was a painting of you")
                                                print("And for a moment I thought you were here")
                                                print("But then again, it wasn't true, dah")
                                                print("\nAnd all this time I have been lyin'")
                                                print("Oh, lyin' in secret to myself")
                                                print("I've been putting sorrow on the farthest place on my shelf")
                                                print("La-di-da")
                                                print()
                                                print(repeat)
                                                print(repeat2)
                                                print(repeat3)
                                                print(repeat4)
                                                print(repeat5)
                                                print("\nBut no, take me home")
                                                print(repeat6)
                                                print(repeat7)
                                                print(repeat9)
                                                print(repeat6)
                                                print(repeat7)
                                                print(repeat9)
                                                print(repeat6)
                                                print(repeat7)
                                                print(repeat8)
                                                print("\nBut I kept runnin' for a soft place to fall")
                                                print(repeat10)
                                                print(repeat10)
                                                print(repeat10)
                                                print()
                                                print(repeat)
                                                print(repeat2)
                                                print("\nBut no, take me home")
                                                print(repeat6)
                                                print(repeat7)
                                                print(repeat9)
                                                print(repeat6)
                                                print(repeat7)
                                                print("\nNo, take me home, home where I belong, no, no")
                                                print("No, take me home, home where I belong, oh, oh, oh")
                                                print("No, take me home, home where I belong, no, no")
                                                print("No, take me home, home where I belong")
                                                print(repeat8)
                                            lyric("And I kept runnin' for a soft place to fall")
                                        lyric("No, take me home")
                                    lyric("I can't take it anymore")
                                lyric("I got no other place to go")
                            lyric("Take me home where I belong")
                        lyric("I felt alive and I can't complain")
                    lyric("And I was dancing in the rain")
                lyric("Nobody knows, nobody knows")
            lyric("Would I run off the world someday?")
        lyric("And I was runnin' far away")
    elif song == "8":
        def lyric(repeat):
            def lyric(repeat2):
                def lyric(repeat3):
                    def lyric(repeat4):
                        def lyric(repeat5):
                            def lyric(repeat6):
                                def lyric(repeat7):
                                    def lyric(repeat8):
                                        def lyric(repeat9):
                                            def lyric(repeat10):
                                                print("\nwe fell in love in october")
                                                print("by girl in red")
                                                print()
                                                print(repeat)
                                                print(repeat2)
                                                print()
                                                print(repeat3)
                                                print(repeat4)
                                                print(repeat5)
                                                print(repeat6)
                                                print()
                                                print(repeat7)
                                                print(repeat8)
                                                print(repeat7)
                                                print(repeat9)
                                                print(repeat10)
                                                print(repeat8)
                                                print()
                                                print(repeat)
                                                print(repeat2)
                                                print("Don't bother looking down")
                                                print("We're not going that way")
                                                print("At least I know, I am here to say")
                                                print()
                                                print(repeat3)
                                                print(repeat4)
                                                print(repeat5)
                                                print(repeat6)
                                                print("(", repeat7, ")")
                                                print()
                                                print(repeat7)
                                                print(repeat8)
                                                print(repeat7)
                                                print(repeat8)
                                                print(repeat7)
                                                print(repeat8)
                                                print(repeat7)
                                                print(repeat8)
                                                print(repeat9)
                                                print(repeat10)
                                                print(repeat8)
                                            lyric("My world, my world, my world")
                                        lyric("You will be my world")
                                    lyric("You will be my girl")
                                lyric("My girl, my girl, my girl")
                            lyric("Admiring from afar")
                        lyric("Looking at the stars")
                    lyric("That's why, I love fall")
                lyric("We fell in love in October")
            lyric("You look so pretty and I love this view")
        lyric("Smoking cigarettes on the roof")
    option = input("\n Would you like more? \n A) Yes \n B) No \n\n [A / B]?: ")
    if option == "B":
        print("\nWe hope you enjoyed the service!")
        break
